version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: dentist
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  application:
    container_name: reservation_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:8080"
    env_file: .env