spring.application.name=lv2-final-mission

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://${PROD_DATABASE_HOST}:${PROD_DATABASE_PORT}/${PROD_DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${PROD_DATABASE_USER}
spring.datasource.password=${PROD_DATABASE_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create
